name: My first pipeline on github ci
on:
  push:
    branches: [main]
  pull_request:

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "running test"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploying"
  
  post-deploy:
    needs: deploy
    runs-on: alpine
    steps:
      - run: echo "post deploy"