name: Node CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20
      - name: multipline command
        run: |
          echo "Line 1"
          echo "line 2"
          npm ci
          npm run build
  